src/alvisarrentas/urls.py
"""alvisarrentas URL Configuration
"""
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^users/', include('django.contrib.auth.urls')),

    url(r'^', include('webapp.urls', namespace='webapp')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/webapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),

    url(r'^contrato/list/$', views.ContratoList.as_view(), name='contrato-list'),
    url(r'^contrato/excel/$', views.ContratoExcel.as_view(), name='contrato-excel'),
    url(r'^contrato/create/$', views.ContratoCreate.as_view(), name='contrato-create'),
    url(r'^contrato/detail/(?P<pk>[0-9]+)/$', views.ContratoDetail.as_view(), name='contrato-detail'),
    url(r'^contrato/update/(?P<pk>[0-9]+)/$', views.ContratoUpdate.as_view(), name='contrato-update'),
    url(r'^contrato/delete/(?P<pk>[0-9]+)/$', views.ContratoDelete.as_view(), name='contrato-delete'),
    url(r'^contrato/facturar/(?P<pk>[0-9]+)/$', views.ContratoFacturar.as_view(), name='contrato-facturar'),

    url(r'^factura/list/$', views.FacturaList.as_view(), name='factura-list'),
    url(r'^factura/zip/$', views.FacturaZip.as_view(), name='factura-zip'),
    url(r'^factura/excel/$', views.FacturaExcel.as_view(), name='factura-excel'),
    url(r'^factura/detail/(?P<pk>[0-9]+)/$', views.FacturaDetail.as_view(), name='factura-detail'),
    url(r'^factura/pagar/(?P<pk>[0-9]+)/$', views.FacturaPagar.as_view(), name='factura-pagar'),
    url(r'^factura/pdf/(?P<pk>[0-9]+)/$', views.FacturaPdf.as_view(), name='factura-pdf'),

    url(r'^pagos/buscar/$', views.PagosBucar.as_view(), name='pagos-buscar'),
    url(
        r'^pagos/consolidar/(?P<fecha_inicial>\d{4}-\d{2}-\d{2})/(?P<fecha_final>\d{4}-\d{2}-\d{2})/$',
        views.PagosConsolidar.as_view(), name='pagos-consolidar'
    ),
]

src/webapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse_lazy

DIAS_MES = (
    (0, 'Factura Manual'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'),
    (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'),
    (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'),
    (26, '26'), (27, '27'), (28, '28'),
)

USO_CFDI = (
    ('P01', u'Por definir'),
    ('G03', u'Gastos en general'),
    ('I01', u'Construcciones'),
    ('I02', u'Mobilario y equipo de oficina por inversiones'),
    ('G01', u'Adquisición de mercancias'),
    ('G02', u'Devoluciones, descuentos o bonificaciones'),
    ('I03', u'Equipo de transporte'),
    ('I04', u'Equipo de computo y accesorios'),
    ('I05', u'Dados, troqueles, moldes, matrices y herramental'),
    ('I06', u'Comunicaciones telefónicas'),
    ('I07', u'Comunicaciones satelitales'),
    ('I08', u'Otra maquinaria y equipo'),
    ('D01', u'Honorarios médicos, dentales y gastos hospitalarios'),
    ('D02', u'Gastos médicos por incapacidad o discapacidad'),
    ('D03', u'Gastos funerales'),
    ('D04', u'Donativos'),
    ('D05', u'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'),
    ('D06', u'Aportaciones voluntarias al SAR'),
    ('D07', u'Primas por seguros de gastos médicos'),
    ('D08', u'Gastos de transportación escolar obligatoria'),
    ('D09', u'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones'),
    ('D10', u'Pagos por servicios educativos (colegiaturas)'),
)

METODO_PAGO = (
    ('PUE', u'Pago en una sola exhibición'),
    ('PPD', u'Pago en parcialidades o diferido'),
)

FORMA_PAGO = (
    ('01', u'Efectivo'),
    ('02', u'Cheque nominativo'),
    ('03', u'Transferencia electrónica de fondos'),
    ('04', u'Tarjeta de crédito'),
    ('05', u'Monedero electrónico'),
    ('06', u'Dinero electrónico'),
    ('08', u'Vales de despensa'),
    ('12', u'Dación en pago'),
    ('13', u'Pago por subrogación'),
    ('14', u'Pago por consignación'),
    ('15', u'Condonación'),
    ('17', u'Compensación'),
    ('23', u'Novación'),
    ('24', u'Confusión'),
    ('25', u'Remisión de deuda'),
    ('26', u'Prescripción o caducidad'),
    ('27', u'A satisfacción del acreedor'),
    ('28', u'Tarjeta de débito'),
    ('29', u'Tarjeta de servicios'),
    ('99', u'Por definir'),
)


class Contrato(models.Model):
    nombre_predio = models.CharField(max_length=100, null=False, blank=False)
    cuenta_predial = models.CharField(max_length=100, null=True, blank=True)

    nombre_cliente = models.CharField(max_length=100, null=False, blank=False)
    rfc_cliente = models.CharField(max_length=13, null=False, blank=False)
    correo_cliente = models.EmailField(null=False, blank=False)
    telefono_cliente = models.CharField(max_length=10, null=True, blank=True)

    saldo_contrato = models.DecimalField(max_digits=20, decimal_places=2, null=False, blank=False, default=0, verbose_name='saldo vencido')
    precio_mensual = models.DecimalField(
        max_digits=20, decimal_places=2, null=False, help_text=u'Ingrese el precio antes de impuestos'
    )
    retener_impuestos = models.BooleanField(
        null=False, default=False, blank=False, help_text=u'Marque esta casilla si desea rentener ISR e IVA'
    )
    uso_cfdi = models.CharField(max_length=3, null=False, default='G03', choices=USO_CFDI)
    metodo_pago = models.CharField(max_length=3, null=False, default='PUE', choices=METODO_PAGO)
    forma_pago = models.CharField(max_length=3, null=False, default='01', choices=FORMA_PAGO)

    dia_facturacion = models.IntegerField(null=False, blank=False, default=1, choices=DIAS_MES)

    fecha_registro = models.DateTimeField(auto_now_add=True)
    fecha_modificado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre_predio

    def __unicode__(self):
        return self.nombre_predio

    def get_absolute_url(self):
        return reverse_lazy('webapp:contrato-detail', kwargs={'pk': self.pk})

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.nombre_predio = self.nombre_predio.upper()
        self.nombre_cliente = self.nombre_cliente.upper()
        self.rfc_cliente = self.rfc_cliente.upper()
        self.correo_cliente = self.correo_cliente.lower()
        super(Contrato, self).save(force_insert, force_update, using, update_fields)


class Configuracion(models.Model):
    nombre = models.CharField(max_length=10, unique=True, null=False, blank=False)
    valor = models.IntegerField(null=False)

    def __unicode__(self):
        return self.nombre

    def __str__(self):
        return self.nombre


class Factura(models.Model):
    uuid = models.UUIDField(unique=True, null=False, db_index=True)
    uuid_rep = models.UUIDField(null=True)
    serie = models.CharField(max_length=10, null=False, blank=False)
    folio = models.IntegerField(null=False)
    fecha = models.DateField(null=False, blank=False)

    nombre_cliente = models.CharField(max_length=100, null=False, blank=False)
    rfc_cliente = models.CharField(max_length=13, null=False, blank=False)
    correo_cliente = models.EmailField(null=False, blank=False)

    concepto = models.CharField(max_length=500, null=False, blank=False)
    sub_total = models.DecimalField(max_digits=20, decimal_places=2, null=False, blank=False, default=0)
    iva_trasladado = models.DecimalField(max_digits=20, decimal_places=2, null=False, blank=False, default=0)
    iva_retenido = models.DecimalField(max_digits=20, decimal_places=2, null=False, blank=False, default=0)
    isr_retenido = models.DecimalField(max_digits=20, decimal_places=2, null=False, blank=False, default=0)
    total = models.DecimalField(max_digits=20, decimal_places=2, null=False, blank=False, default=0)

    contrato = models.ForeignKey('webapp.Contrato', null=True, on_delete=models.SET_NULL)

    pagada = models.BooleanField(null=False, default=False)
    fecha_pago = models.DateField(null=True, blank=True)
    forma_pago_rep = models.CharField(max_length=2, null=True, blank=True, choices=FORMA_PAGO)
    num_operacion = models.CharField(max_length=100, null=True, blank=True)

    pdf = models.FileField(upload_to='facturas', null=False)
    xml = models.FileField(upload_to='facturas', null=False)
    pdf_rep = models.FileField(upload_to='rep', null=True)
    xml_rep = models.FileField(upload_to='rep', null=True)

    fecha_registro = models.DateTimeField(auto_now_add=True)
    fecha_modificado = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.concepto

    def __str__(self):
        return self.concepto

    def get_absolute_url(self):
        return reverse_lazy('webapp:factura-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-id']

src/webapp/forms.py
# -*- coding: utf-8 -*-
from django import forms

from webapp.models import FORMA_PAGO

class FacturaPagarForm(forms.Form):
    fecha_pago = forms.DateField(
        required=True,
        help_text=u'Al marcar esta factura como pagada se descontara el saldo del contrato.'
    )
    forma_pago_rep = forms.ChoiceField(FORMA_PAGO, required=True)
    num_operacion = forms.CharField(max_length=100, required=True)


class FacturarForm(forms.Form):
    concepto = forms.CharField(max_length=500, strip=True, required=True)
    sub_total = forms.DecimalField(
        decimal_places=2, max_digits=20, required=True,
        help_text=u'Ingrese el precio antes de impuestos'
    )


class FacturaExcelForm(forms.Form):
    fecha_inicial = forms.DateField(required=True)
    fecha_final = forms.DateField(required=True)


class FacturaExcelZip(forms.Form):
    fecha_inicial = forms.DateField(required=True)
    fecha_final = forms.DateField(required=True)


class PagoBuscarForm(forms.Form):
    fecha_inicial = forms.DateField(required=True)
    fecha_final = forms.DateField(required=True)
    estado_de_cuenta = forms.FileField(required=False, allow_empty_file=False)


class PagoConsolidarForm(forms.Form):
    id_factura = forms.CharField(required=True, widget=forms.HiddenInput())
    fecha_factura = forms.CharField(required=False, disabled=True)
    uuid = forms.CharField(required=False, disabled=True)
    folio = forms.CharField(required=False, disabled=True)
    nombre_cliente = forms.CharField(required=False, disabled=True)
    rfc_cliente = forms.CharField(required=False, disabled=True)
    concepto = forms.CharField(required=False, disabled=True)
    total = forms.DecimalField(decimal_places=2, max_digits=20, required=False, disabled=True)
    moviento_cuenta = forms.CharField(required=False, disabled=True,
                                      widget=forms.Textarea(attrs={'rows': 3, 'cols': 75}))
    fecha_pago = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

src/webapp/templates/webapp/base.html
{% load staticfiles %}
<!doctype html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="es"/>
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>

    <title>{% block title %}ALVISAR Rentas{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">

    <link href="{% static 'css/toastr.css' %}" rel="stylesheet"/>

    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet"/>
    {% block links %}{% endblock %}

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

    <script src="{% static 'js/toastr.min.js' %}"></script>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    {% block scripts %}{% endblock %}

    <script type="text/javascript">
        $(function () {
            {% for message in messages %}
                toastr.{{ message.tags }}('{{ message }}');
            {% endfor %}
        });
    </script>

</head>

<body class="">
<div class="page">
    <div class="page-main">
        <div class="header py-4">
            <div class="container">
                <div class="d-flex">
                    <a class="header-brand" href="{% url 'webapp:index' %}">
                        <img src="{% static 'img/favicon.ico' %}" class="header-brand-img" alt="tabler logo"> ALVISAR
                        Rentas
                    </a>

                    <div class="d-flex order-lg-2 ml-auto">
                        <div class="dropdown">
                            <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                                <span class="avatar"></span>
                                    <span class="ml-2 d-none d-lg-block">
                                    <span class="text-default">{{ user }}</span>
                                    <small class="text-muted d-block mt-1">{% now "d/m/Y" %}</small>
                                    </span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    <i class="dropdown-icon fe fe-log-out"></i> Sign out
                                </a>
                            </div>
                        </div>
                    </div>
                    <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse"
                       data-target="#headerMenuCollapse">
                        <span class="header-toggler-icon"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg order-lg-first">
                        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                            <li class="nav-item">
                                <a href="{% url 'webapp:index' %}" class="nav-link menu"><i class="fe fe-home"></i>
                                    Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'webapp:contrato-list' %}" class="nav-link menu"><i
                                        class="fe fe-box"></i>
                                    Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'webapp:factura-list' %}" class="nav-link menu"><i class="fe fe-book"></i>
                                    CFDIs</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'webapp:pagos-buscar' %}" class="nav-link menu"><i class="fe fe-dollar-sign"></i>
                                    Conciliación</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="my-3 my-md-5">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-auto ml-lg-auto">
                    <div class="row align-items-center">
                        <div class="col-auto">
                            <ul class="list-inline list-inline-dots mb-0">
                                <li class="list-inline-item"><a href="#">Manual</a></li>
                                <li class="list-inline-item"><a href="#">Preguntas y Respuestas</a></li>
                            </ul>
                        </div>
                        <div class="col-auto">
                            <a href="http://alvisar.com/" class="btn btn-outline-primary btn-sm">Alvisar</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
                    Todos los derechos reservados <a href="mailto:iturrios3063@gmail.com">Ing. Luis Iturrios</a>
                </div>
            </div>
        </div>
    </footer>
</div>
</body>

</html>

src/webapp/templates/webapp/contrato-create.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fe fe-box"></i> Nuevo contrato</h3>
                    </div>
                    <div class="card-body">
                        {% bootstrap_messages %}
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'webapp:contrato-list' %}" class="btn btn-secondary"><i
                                class="fe fe-skip-back"></i>
                            Regresar</a>
                        <button type="reset" class="btn btn-primary"><i class="fe fe-refresh-ccw"></i> Limpiar</button>
                        <button type="submit" class="btn btn-success"><i class="fe fe-plus"></i> Agregar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/webapp/templates/webapp/contrato-detail.html
{% extends 'webapp/base.html' %}
{% load humanize %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"><i class="fe fe-box"></i> {{ contrato }}</h3>
                </div>
                <div class="card-body">
                    <p><strong>Nombre predio:</strong> {{ contrato.nombre_predio }}</p>

                    <p><strong>Cuenta predial:</strong> {{ contrato.cuenta_predial }}</p>

                    <p><strong>Nombre cliente:</strong> {{ contrato.nombre_cliente }}</p>

                    <p><strong>Rfc cliente:</strong> {{ contrato.rfc_cliente }}</p>

                    <p><strong>Correo cliente:</strong> {{ contrato.correo_cliente }}</p>

                    <p><strong>Telefono cliente:</strong> {{ contrato.telefono_cliente }}</p>

                    <p><strong>Saldo contrato:</strong> {{ contrato.saldo_contrato | intcomma }}</p>

                    <p><strong>Precio mensual:</strong> ${{ contrato.precio_mensual | intcomma }}</p>

                    <p><strong>Retener Impuestos:</strong> {% if contrato.retener_impuestos %}SI{% else %}NO{% endif %} </p>

                    <p><strong>Uso CFDI:</strong> {{ contrato.get_uso_cfdi_display }} </p>

                    <p><strong>Metodo de Pago:</strong> {{ contrato.get_metodo_pago_display }} </p>

                    <p><strong>Forma de Pago:</strong> {{ contrato.get_forma_pago_display }} </p>

                    <p><strong>Dia facturacion:</strong> {{ contrato.get_dia_facturacion_display }}</p>
                </div>
                <div class="card-footer text-right">
                    <a href="{% url 'webapp:contrato-list' %}" class="btn btn-secondary"><i class="fe fe-skip-back"></i>
                        Regresar</a>
                    <a href="{% url 'webapp:contrato-delete' pk=contrato.pk %}" class="btn btn-danger"><i
                            class="fe fe-trash"></i> Borrar</a>
                    <a href="{% url 'webapp:contrato-update' pk=contrato.pk %}" class="btn btn-success"><i
                            class="fe fe-edit"></i> Editar</a>
                    <a href="{% url 'webapp:contrato-facturar' pk=contrato.pk %}" class="btn btn-primary"><i
                            class="fe fe-book"></i> Generar Factura</a>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"><i class="fe fe-book"></i> Ultimos CFDIs</h3>
                </div>
                <div class="card-body">
                    <div class="table-container table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Folio</th>
                                <th>Fecha</th>
                                <th>Pago</th>
                                <th>Concepto</th>
                                <th>Sub Total</th>
                                <th>Total</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for factura in contrato.factura_set.all %}
                                <tr>
                                    <td>
                                        <a href="{{ factura.get_absolute_url }}"><b>{{ factura.serie }}</b> {{ factura.folio }}
                                        </a></td>
                                    <td>{{ factura.fecha | date:'d/m/Y' }}</td>
                                    <td>{{ factura.fecha_pago | date:'d/m/Y' }}</td>
                                    <td>{{ factura.concepto }}</td>
                                    <td>${{ factura.sub_total | intcomma }}</td>
                                    <td>${{ factura.total | intcomma }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/webapp/templates/webapp/contrato-list.html
{% extends 'webapp/base.html' %}
{% load humanize %}
{% load django_tables2 %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"><i class="fe fe-box"></i> Contratos</h3>

                    <div class="card-options">
                        <a href="{% url 'webapp:contrato-create' %}" class="btn btn-success btn-sm"><i
                                class="fe fe-plus"></i> Agregar</a>
                        &nbsp;
                        <a href="{% url 'webapp:contrato-excel' %}" class="btn btn-success btn-sm"><i
                                class="fe fe-download"></i> Excel</a>
                    </div>
                </div>
                <div class="card-body">
                    {% if filter %}
                        <form method="get" class="form-inline">
                            {% bootstrap_form filter.form layout='inline' %}
                            &nbsp;
                            <button type="submit" class="btn btn-primary">Buscar</button>
                            &nbsp;
                            <a class="btn btn-secondary" href="{% url 'webapp:factura-list' %}">Limpiar</a>
                        </form>
                    {% endif %}

                    {% render_table table %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/webapp/templates/webapp/factura-excel.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fe fe-book"></i> Facturas Excel</h3>
                    </div>
                    <div class="card-body">
                        {% bootstrap_messages %}
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'webapp:factura-list' %}" class="btn btn-secondary"><i
                                class="fe fe-skip-back"></i> Regresar</a>
                        <button type="submit" class="btn btn-success"><i class="fe fe-edit"></i> Generar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(function () {
            $("#id_fecha_inicial").attr("type", "date");
            $("#id_fecha_final").attr("type", "date");
        });
    </script>
{% endblock %}

src/webapp/templates/webapp/factura-zip.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fe fe-book"></i> Facturas Zip</h3>
                    </div>
                    <div class="card-body">
                        {% bootstrap_messages %}
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'webapp:factura-list' %}" class="btn btn-secondary"><i
                                class="fe fe-skip-back"></i> Regresar</a>
                        <button type="submit" class="btn btn-success"><i class="fe fe-edit"></i> Generar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(function () {
            $("#id_fecha_inicial").attr("type", "date");
            $("#id_fecha_final").attr("type", "date");
        });
    </script>
{% endblock %}

src/webapp/templates/webapp/index.html
{% extends 'webapp/base.html' %}

{% block content %}
    <div class="page-header">
        <h1 class="page-title">
            {{ razon_social }}
        </h1>
    </div>
    <div class="row row-cards">
        <div class="col-sm-6 col-lg-3">
            <div class="card p-3">
                <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-red mr-3">
                      <i class="fe fe-box"></i>
                    </span>

                    <div>
                        <h4 class="m-0"><a href="{% url 'webapp:contrato-list' %}">Clientes
                        </a></h4>
                        <small class="text-muted">Contratos por clientes</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3">
            <div class="card p-3">
                <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-blue mr-3">
                      <i class="fe fe-book"></i>
                    </span>

                    <div>
                        <h4 class="m-0"><a href="{% url 'webapp:factura-list' %}">CFDIs
                        </a></h4>
                        <small class="text-muted">Administración de CFDIs</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3">
            <div class="card p-3">
                <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-yellow mr-3">
                      <i class="fe fe-dollar-sign"></i>
                    </span>

                    <div>
                        <h4 class="m-0"><a href="{% url 'webapp:pagos-buscar' %}">Conciliación
                        </a></h4>
                        <small class="text-muted">Conciliación bancaria</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/webapp/templates/webapp/pagos-buscar.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fe fe-search"></i> Buscar facturar por pagar</h3>
                    </div>
                    <div class="card-body">
                        <p>Mediante este esquema no se genera el REP</p>
                        {% bootstrap_messages %}
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    </div>
                    <div class="card-footer text-right">
                        <a href="{{ factura.get_absolute_url }}" class="btn btn-secondary"><i
                                class="fe fe-skip-back"></i> Regresar</a>
                        <button type="reset" class="btn btn-primary"><i class="fe fe-refresh-ccw"></i> Limpiar</button>
                        <button type="submit" class="btn btn-success"><i class="fe fe-search"></i> Buscar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(function () {
            $("#id_fecha_inicial").attr("type", "date");
            $("#id_fecha_final").attr("type", "date");
        });
    </script>
{% endblock %}